
import type { Metadata } from "next";
import { Geist, Geist_Mono, Quicksand } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const quicksand = Quicksand({
  subsets: ["latin"],
  variable: "--font-jazz",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${geistSans.variable} ${geistMono.variable} ${quicksand.variable}`}
        style={{ minHeight: "100vh", position: "relative", overflowX: "hidden" }}
      >
        {/* Animated background layer */}
        <div
          aria-hidden="true"
          className="fixed inset-0 -z-10 pointer-events-none animate-bg-move"
          style={{
            background:
              "radial-gradient(circle at 20% 40%, #4B2067 0%, transparent 60%)," +
              "radial-gradient(circle at 80% 60%, #FFD700 0%, transparent 60%)," +
              "radial-gradient(circle at 50% 90%, #191970 0%, transparent 70%)",
            opacity: 0.25,
            width: "100vw",
            height: "100vh",
            transition: "background 1s linear"
          }}
        />
        {children}
      </body>
    </html>
  );
}
